### ISSUE TITLE
EveStaticData: GroupId of invType is 0

### ISSUE THREAD

**Issue by Bounz** [ezet/evelib#39]
Hi!
I need to get GroupId of bluebprunt, so I'm using the following code:
```
var estd = new EveStaticData();
var invType = estd.GetInvType(bp.TypeId);
```
But after request is finished `invType.GroupId` is 0, but `invType.Group` has a valid URL to element-43.com API endpoint.

**Comment by ezet** [comment]
Yeah, the EveStaticData is incomplete and hasn't been looked at in a long time. The source doesn't return the group ID as xml, so you'll have to extract the ID from the end of the group URI. This is what I had in mind when creating it, but I've since stopped the development of it. You can easily do it yourself though.
