### ISSUE TITLE
Unit Tests not passing

### ISSUE THREAD

**Issue by ScottF1** [ezet/evelib#40]
Hi - I am new to this repo.  I am not sure if this is the right place to ask for help?  I just cloned and built the solution.  I ran all the unit tests and 49 to 50 are failing.  There are some common causes of failure:
* Authenticate gets System.Net.WebException: The remote server returned an error: (400) Bad Request.
* Many others get eZet.EveLib.EveXmlModule.Exceptions.EveXmlException: Key has expired. Contact key owner for access renewal. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
* And eZet.EveLib.EveCrestModule.Exceptions.EveCrestException: This is not third party enabled... yet ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
* System.NullReferenceException: Object reference not set to an instance of an object. (I expect these are related to above failures)

Any help or tips would be much appreciated.

Cheers,
Scott

**Comment by ezet** [comment]
The two first are probably related, you would have to enter in valid authentication details for them to pass. The 3rd is simply not enabled by ccp yet, the last one is probably related to any of the above.

**Comment by ScottF1** [comment]
Thanks for your feedback.  I suspected I may have to generate my own auth token to get some of the tests to pass but wanted to check before making modifications to the code/tests.
While I have your attention...can any of the evelib libraries be used to access the eve data dump provided by ccp?  Specifically the YAML files and sql database?

**Comment by ezet** [comment]
Yeah, you'll need your own auth token since they do expire. It seems like
the keys for EveXml tests has expired too, which caused some of the
exceptions.
EveLib doesn't handle the SDE or yaml files, no. The EveStaticData library
can be used to access element-43.com which provides most of the SDE data,
but that library isn't complete at all, it only supports 1 or 2 resources.
It also isn't suitable for large amounts of data since its all xml, so for
that youd want your own db. But if you're dealing with small amounts of
data it's great, and if you want you can continue the implementation for
the resources you need yourself. It's pretty straight forward to do, and
only takes a couple of minutes.

**Comment by ScottF1** [comment]
Great stuff.  I'll look at getting my own token to use those libraries.  I have started working on classes to deal with local static data dump (YAML and SQL).  If I think they're good enough I'll put up a pull request for you to look over and incorporate anything you think may add value to this project.
